package com.mycompany.inventorymanager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author qasem
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Inventory Management System");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        project_title = new javax.swing.JLabel();
        selction_title = new javax.swing.JLabel();
        selction = new javax.swing.JComboBox<>();
        Continue = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(null);

        project_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        project_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        project_title.setText("Inventory Management System");
        getContentPane().add(project_title);
        project_title.setBounds(6, 32, 500, 32);

        selction_title.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        selction_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selction_title.setText("Select Your Role: ");
        getContentPane().add(selction_title);
        selction_title.setBounds(139, 113, 217, 27);

        selction.setFont(new java.awt.Font("Segoe UI", 3, 17)); // NOI18N
        selction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier", "Manager", "Buyer", " " }));
        selction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selctionActionPerformed(evt);
            }
        });
        getContentPane().add(selction);
        selction.setBounds(178, 184, 137, 45);

        Continue.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\forward.png")); // NOI18N
        Continue.setText("Continue");
        Continue.setName(""); // NOI18N
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        getContentPane().add(Continue);
        Continue.setBounds(329, 299, 145, 71);

        Exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\logout.png")); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(33, 299, 145, 71);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void selctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selctionActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
        String role = (String)selction.getSelectedItem();

        if (selction.getSelectedIndex() == 3) { // " " is selected
            JOptionPane.showMessageDialog(this, "Please select a role!");
            return; // Stop execution if no valid role is selected
        }

        this.dispose(); // Close current window instead of just hiding

        switch(role.trim()) { // trim() removes any whitespace
            case  "Supplier":
            new SupplierLoginFrame().setVisible(true);
            break;
            case "Manager":
            // Uncomment when ManagerFrame is ready
            // new ManagerFrame().setVisible(true);
            new ManagerFrame().setVisible(true);
            break;
            case "Buyer":
            new BuyerFrame().setVisible(true);
            break;
        }

    }//GEN-LAST:event_ContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JButton Exit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel project_title;
    private javax.swing.JComboBox<String> selction;
    private javax.swing.JLabel selction_title;
    // End of variables declaration//GEN-END:variables

    
    
    
    
}
