package com.mycompany.inventorymanager;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 *
 * @author qasem
 */
public class SupplierFrame extends javax.swing.JFrame {
    private Supplier supplier;

    /**
     * Creates new form SupplierFrame
     */
    public SupplierFrame(Supplier supplier) {
        initComponents();
        this.supplier= supplier;
        setTitle("Supplier Dashboard - " + supplier.getSupplierName());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductButton = new javax.swing.JButton();
        removeProductButton = new javax.swing.JButton();
        viewMyProductsButton = new javax.swing.JButton();
        productCountButton = new javax.swing.JButton();
        searchByIdButton = new javax.swing.JButton();
        searchByNameButton = new javax.swing.JButton();
        myInformationButton = new javax.swing.JButton();
        previousPageButton = new javax.swing.JButton();
        exitApplicationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addProductButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\icons8-add-pulsar-color\\icons8-add-96.png")); // NOI18N
        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        removeProductButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\remove.png")); // NOI18N
        removeProductButton.setText("Remove Product");
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });

        viewMyProductsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\supplier (1).png")); // NOI18N
        viewMyProductsButton.setText("View My Products");
        viewMyProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyProductsButtonActionPerformed(evt);
            }
        });

        productCountButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\box.png")); // NOI18N
        productCountButton.setText("Product Count");
        productCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCountButtonActionPerformed(evt);
            }
        });

        searchByIdButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\serch.png")); // NOI18N
        searchByIdButton.setText("Search By ID");
        searchByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdButtonActionPerformed(evt);
            }
        });

        searchByNameButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\serch.png")); // NOI18N
        searchByNameButton.setText("Search By Name");
        searchByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByNameButtonActionPerformed(evt);
            }
        });

        myInformationButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\identification-card.png")); // NOI18N
        myInformationButton.setText("My Information");
        myInformationButton.setMaximumSize(new java.awt.Dimension(185, 71));
        myInformationButton.setMinimumSize(new java.awt.Dimension(185, 71));
        myInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myInformationButtonActionPerformed(evt);
            }
        });

        previousPageButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\right-arrow.png")); // NOI18N
        previousPageButton.setText("Previous Page");
        previousPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPageButtonActionPerformed(evt);
            }
        });

        exitApplicationButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\logout.png")); // NOI18N
        exitApplicationButton.setText("Exit Application");
        exitApplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO V15\\Downloads\\welcome-back (1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewMyProductsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(248, 252, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeProductButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitApplicationButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(productCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exitApplicationButton, myInformationButton, previousPageButton, removeProductButton, viewMyProductsButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeProductButton)
                    .addComponent(addProductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByNameButton)
                .addGap(18, 18, 18)
                .addComponent(searchByIdButton)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewMyProductsButton)
                    .addComponent(myInformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(productCountButton)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousPageButton)
                    .addComponent(exitApplicationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addProductButton, removeProductButton, searchByIdButton, searchByNameButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exitApplicationButton, myInformationButton, productCountButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {previousPageButton, viewMyProductsButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed
        // TODO add your handling code here:
        String productId = JOptionPane.showInputDialog(this,
            "Enter product ID to remove:",
            "Remove Product",
            JOptionPane.QUESTION_MESSAGE);
    
        if (productId != null && !productId.isEmpty()) {
            // Store current inventory state
            int initialCount = supplier.getSupplierProductsCount();
        
            // Attempt removal
            supplier.removeProductFromSupplier(productId);
        
            // Check if count changed
            if (supplier.getSupplierProductsCount() < initialCount) {
                JOptionPane.showMessageDialog(this,
                    "Product removed successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this,
                    "Failed to remove product (invalid ID or quantity is 0)",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_removeProductButtonActionPerformed

    private void viewMyProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyProductsButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        for (Product product : supplier.productsInventory) {
            sb.append(String.format(
                "%s (ID: %s)\nQuantity: %d\nPrice: $%.2f\n\n",
                product.getName(), product.getID(), product.getQuantity(), product.getPrice()));
        }
        JOptionPane.showMessageDialog(this,
            sb.toString(),
            "My Products",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viewMyProductsButtonActionPerformed

    private void productCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCountButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            "Total products in inventory: " + supplier.getSupplierProductsCount(),
            "Product Count",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_productCountButtonActionPerformed

    private void searchByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdButtonActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog(this,
            "Enter product ID to search:",
            "Search by ID",
            JOptionPane.QUESTION_MESSAGE);
    
        if (id != null && !id.isEmpty()) {
            supplier.searchForProductById(id);
        }
    }//GEN-LAST:event_searchByIdButtonActionPerformed

    private void searchByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByNameButtonActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(this,
            "Enter product name to search (Keyboard , Mouse , Screen) :",
            "Search by Name",
            JOptionPane.QUESTION_MESSAGE);
    
        if (name != null && !name.isEmpty()) {
            supplier.searchForProductByName(name);
        }
    }//GEN-LAST:event_searchByNameButtonActionPerformed

    private void myInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myInformationButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
            supplier.toString(),
            "My Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_myInformationButtonActionPerformed

    private void previousPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPageButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close current window
        new SupplierLoginFrame().setVisible(true); // Return to login
    }//GEN-LAST:event_previousPageButtonActionPerformed

    private void exitApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to exit?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION);
    
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitApplicationButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        String[] options = {"Keyboard (0)", "Mouse (1)", "Screen (2)"};
        int choice = JOptionPane.showOptionDialog(this,
            "Select product to add:",
            "Add Product",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);

        if (choice >= 0) {
            supplier.addProductToSupplier(choice);
            JOptionPane.showMessageDialog(this,
                "Added 1 " + options[choice] + " to inventory",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Supplier defaultSupplier= new Supplier("Qa", "Qasem", "777");
                new SupplierFrame(defaultSupplier).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton exitApplicationButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton myInformationButton;
    private javax.swing.JButton previousPageButton;
    private javax.swing.JButton productCountButton;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JButton searchByIdButton;
    private javax.swing.JButton searchByNameButton;
    private javax.swing.JButton viewMyProductsButton;
    // End of variables declaration//GEN-END:variables
}
